version: "3"
name: "katt"

services:
  kattapp:
    container_name: kattapp
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./app/.docker/Dockerfile
    command: [ "npm", "run", "start" ]
